name: Aprendiendo github actions
run-name: Estoy aprendiendo github actions!!!

on: [push]
jobs:
#  setup-java:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/@Checkout@v2

      - name: Mostrar version de linux
        run:  uname -a

      - name: Ejecutar script en shell
        run: |
            echo "Hola desde Linux ubuntu"
            ls -altr